import numpy as np
a1-np.array([1,3,5,7,9])
a2=np.array([2,4,6,8,10])
print(a1,a2, sep='\n')
print ("\nAddition")
print(a1+a2)
print ("\nSubtraction")
print (a1-a2)
print("\nMultiplication")
print(al*a2)
print("\nDivision")
print(a1//a2)
print("\nDot Product")
print(a1.dot (a2))
